### PR TITLE
Handle Frameworks folder

### LINKED ISSUE #7: [Bug] Apps with Frameworks folder not being signed correctly
These are the logs when attempting to install IG ++ 

image

### LINKED ISSUE #18: Error when sideloading apps (EXC_BAD_ACCESS)
As the title says, whenever I try to sideload an app using the beta, i.e GBA4iOS, Cercube, Rocket for ig, etc., it crashes after around 5 seconds with no communication to AltServer in that time. I can send crash logs, if that would be helpful. And for the device, it's an iPhone XR on iOS 13.1, and all the apps listed above can be sideloaded just fine with impactor

### PR DESCRIPTION
**Pull request by eni9889**
Fixes https://github.com/rileytestut/AltStore/issues/7
Fixes https://github.com/rileytestut/AltStore/issues/18

### CODE REVIEW

**Comment by mo0o5** [comment]
👍🏻

**Comment by sy6sy2** [comment]
Any news concerning this PR?

**Comment by almoshaks69** [comment]
H

**Comment by lonkelle** [comment]
Has conflicts, and signing frameworks works fine, at least now. 😅

**Comment by sy6sy2** [comment]
Any way to fix conflicts and merge this PR? 😕 A lot of apps use frameworks binaries, would be very nice to have AltStore working with them.

**Comment by lonkelle** [comment]
@sy6sy2 Do you have an example IPA with an embedded framework that doesn’t installl? Because I don’t have any issues with that anymore which is why I closed this.

**Comment by sy6sy2** [comment]
Last time I tried AltStore I wasn't able to run Kodi because of the no-signed frameworks binaries.
You will find here https://we.tl/t-BBU74DHKVd the IPA file I made from the official deb file found here http://mirrors.kodi.tv/releases/darwin/ios-arm64/org.xbmc.kodi-ios_19.1-0_iphoneos-arm64.deb

**Comment by tristan-k** [comment]
@sy6sy2 Is there another way to install Kodi on tvOS without AltStore? Just tried it with XCode and iOS AppSigner but it still fails?

**Comment by sy6sy2** [comment]
@tristan-k If you are jailbroken then just install the deb file.
Else, you can find all kind of singing services on internet, but I never tried them...
The official way to install it is indeed the Xcode+AppSigner way, see https://kodi.wiki/view/HOW-TO:Install_Kodi_on_Apple_TV_4_and_5_(HD_and_4K) if you have any issue, please use the official forum https://forum.kodi.tv/forumdisplay.php?fid=137 😉

**Comment by dimitry-ishenko** [comment]
Sorry for beating a dead horse. @lonkelle were you able to test the Kodi app mentioned by @sy6sy2 ? I am interested in running Kodi on an iPad, but before I waste a bunch of time trying, wanted to check here

**Comment by michael1900** [comment]
Problem with kodi is still there. How to fix this signing problem?

**Pull request closed without merging**
